server:
  port: 8090
spring:
  application:
    name: o2
  # datasource 설정
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: oeuser
    password: 1234

# mybatis 설정
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 마이바티스 디버깅
logging:
  level:
    com:
      o2:
        site:
          half:
            dao: trace

# 경로 설정
file:
  dir: /uploads/