server:
  port: 8090
spring:
  application:
    name: o2
  # datasource 설정
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: scott
    password: tiger

# mybatis 설정
mybatis:
  configuration:
    map-underscore-to-camel-case: true
